
- name: Ensure install directory exists
  file:
    path: "{{ install_dir }}"
    state: directory
    mode: u=rwX,g=rX,o-rwX
    owner: nexus
    group: nexus

- name: Extract packages
  unarchive:
    src: "{{ release_url[ansible_system] }}"
    dest: "{{ install_dir }}"
    remote_src: yes
    list_files: yes
    creates: "{{ install_dir }}/sonatype-work"
  register: extracted_package
  become: yes
  become_user: nexus

- name: Set current version symlink
  file:
    src: "{{ install_dir }}/{{ extracted_package.files | map('dirname') | map('regex_search', item) | select() | first }}"
    dest: "{{ install_dir }}/current"
    mode: u=rwX,g=rX,o-rwX
    owner: nexus
    group: nexus
    state: link
  with_items: '^nexus-\d+(\.\d+)+(-\d+)?$'
